---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/bazarr
              tag: 1.3.0
              pullPolicy: IfNotPresent
            probes:
              liveness:
                spec:
                  timeoutSeconds: 2
              readiness:
                spec:
                  timeoutSeconds: 2
              startup:
                spec:
                  timeoutSeconds: 2
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 568
      PGID: 1003
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "subtitles"
          hajimari.io/info: "Subtitles"
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: bazarr-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        type: pvc
        existingClaim: bazarr-config-v1
      media:
        enabled: true
        mountPath: /media
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1G
