---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 10.2.0
  interval: 10m0s
  values:
    env:
      TZ: Europe/Rome
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 80
            targetPort: 6767
    persistence:
      config:
        enable: true
        skipuninstall: true
        mountPath: /media
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/user/media/test"
            server: "${UNRAID_ADDR}"
      # media:
      #   enabled: true
      #   mountPath: /media
      #   type: custom
      #   volumeSpec:
      #     nfs:
      #       path: "/mnt/user/media"
      #       server: "${UNRAID_ADDR}"
