---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: bazarr
      version: 10.6.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v1.1.1
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "subtitles"
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: bazarr-config-v1
      media:
        enabled: true
        mountPath: /media
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media"
            server: "${TRUENAS_ADDR}"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 1003
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1G
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
