---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 10.2.0
  interval: 10m0s
  values:
    env:
      TZ: Europe/Rome
    service:
      main:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: longhorn
      media:
        enabled: true
        mountPath: /media
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/user/media"
            server: "${UNRAID_ADDR}"
    podSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
