---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lancache-data-v1
  namespace: infrastructure
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
