---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lancache
  namespace: infrastructure
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: lancache
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      # Currently no arm64 image
      repository: lancachenet/monolithic
      tag: latest
      pullPolicy: Always
    env:
      TZ: "Europe/Rome"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${LANCACHE_ADDR}"
    persistence:
      data:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: longhorn
    resources:
      limits:
        memory: 100Mi
        cpu: 50m
