---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lancache
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: lancache
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      # Currently no arm64 image (https://github.com/lancachenet/monolithic/issues/21)
      repository: lancachenet/monolithic
      tag: latest
      pullPolicy: Always
    env:
      TZ: "${TIMEZONE}"
      UPSTREAM_DNS: "8.8.8.8 8.8.4.4"
      CACHE_MEM_SIZE: 128m
      CACHE_DISK_SIZE: 49000m
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_LANCACHE_ADDR}"
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: lancache-data-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 600Mi
