---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
    resources:
      requests:
        cpu: 15m
        memory: 25M
      limits:
        cpu: 15m
        memory: 25M
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - home-cloud
          - infrastructure
          - media
          - monitoring
      name: You
      title: Hajimari
      lightTheme: paper
      darkTheme: espresso
      showGreeting: true
      showAppGroups: true
      showAppUrls: true
      showAppInfo: true
      showAppStatus: true
      defaultAppIcon: mdi:application
      showBookmarkGroups: true
      showGlobalBookmarks: true
      alwaysTargetBlank: false
      defaultSearchProvider: Google
      searchProviders:
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
        - name: IMDB
          token: i
          icon: simple-icons:imdb
          searchUrl: https://www.imdb.com/find?q={query}
          url: https://www.imdb.com
        - name: Reddit
          token: r
          icon: simple-icons:reddit
          searchUrl: https://www.reddit.com/search?q={query}
          url: https://www.reddit.com
        - name: YouTube
          token: 'y'
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
      # customApps:
      #   - group: Media
      #     apps:
      #       - name: Test
      #         url: 'https://example.com'
      #         icon: 'mdi:test-tube'
      #         info: This is a test app
      globalBookmarks:
        - group: Communicate
          bookmarks:
            - name: Discord
              url: 'https://discord.com'
            - name: Gmail
              url: 'http://gmail.com'
        - group: Dev
          bookmarks:
            - name: Codepen
              url: 'https://codepen.io/'
            - name: Devdocs
              url: 'https://devdocs.io'
            - name: Devhints
              url: 'https://devhints.io'
        - group: Media
          bookmarks:
            - name: Spotify
              url: 'http://browse.spotify.com'
            - name: Trakt
              url: 'http://trakt.tv'
            - name: YouTube
              url: 'https://youtube.com/feed/subscriptions'
        - group: Reading
          bookmarks:
            - name: Instapaper
              url: 'https://www.instapaper.com/u'
            - name: Medium
              url: 'http://medium.com'
            - name: Reddit
              url: 'http://reddit.com'
        - group: Tech
          bookmarks:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: TheNextWeb
              url: 'https://thenextweb.com/'
            - name: MIT Technology Review
              url: 'https://www.technologyreview.com/'
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: hajimari-tls
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: false
        # accessMode: ReadWriteOnce
        # size: 1Gi
