---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        cpu: 15m
        memory: 105M
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - home-cloud
          - infrastructure
          - media
          - monitoring
      customApps:
        - name: HDHomeRun
          url: "http://192.168.150.30"
          icon: "antenna"
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
        - name: Reading
          links:
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-1"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: hajimari-tls
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
