---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: infrastructure
spec:
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Rome"
    service:
      main:
        type: LoadBalancer
    resources:
      limits:
        memory: 100Mi
        cpu: 50m
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - infrastructure
          - media
          - monitoring
      customApps:
        - name: HDHomeRun
          url: "http://192.168.150.30"
          icon: "antenna"
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
        - name: Reading
          links:
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          # - host: "hajimari.${SECRET_PUBLIC_DOMAIN}"
          - host: "hajimari.test"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              # - "hajimari.${SECRET_PUBLIC_DOMAIN}"
              - "hajimari.test"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
