---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/lidarr
              tag: 1.4.5
              pullPolicy: IfNotPresent
            probes:
              liveness:
                spec:
                  timeoutSeconds: 2
              readiness:
                spec:
                  timeoutSeconds: 2
              startup:
                spec:
                  timeoutSeconds: 2
            env:
              TZ: ${TIMEZONE}
              PUID: 568
              PGID: 1003
            resources:
              requests:
                cpu: 15m
                memory: 0.5G
              limits:
                # cpu: 500m
                memory: 1G
        strategy: Recreate
    service:
      main:
        controller: main
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "music-box"
          hajimari.io/info: "Music"
        hosts:
          - host: &host "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: lidarr-tls
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: lidarr-config-v1
        globalMounts:
          - path: /config
      music:
        enabled: true
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        globalMounts:
          - path: /music
            subPath: Music
      downloads:
        enabled: true
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/downloads
        globalMounts:
          - path: /downloads
            subPath: complete/music
