---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-config-v1
  namespace: home-cloud
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-sync-v1
  namespace: home-cloud
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
