---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resilio-sync
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: resilio-sync
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/linuxserver/resilio-sync
      tag: version-2.7.2.1375
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    service:
      bt-tcp:
        enabled: true
      bt-udp:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "sync"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - host: &host "resilio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      # -- Where resilio-sync should store its config file.
      config:
        enabled: true
        type: pvc
        existingClaim: resilio-config-v1
      # # -- Folder for downloads/cache.
      # downloads:
      #   enabled: true
      #   type: pvc
      #   existingClaim: resilio-downloads-v1
      # -- Sync folders root.
      data:
        enabled: true
        type: pvc
        existingClaim: resilio-data-v1
    resources:
      # requests:
      #   memory: 400Mi
      #   cpu: 100m
      # limits:
      #   memory: 1Gi
