---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vlmcsd
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: mikolatero/vlmcsd
              tag: latest
              pullPolicy: Always
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
              limits:
                cpu: 10m
                memory: 250Mi
        strategy:
          type: Recreate
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_VLMCSD_ADDR}
        ports:
          http:
            port: 1688
