---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  chart:
    spec:
      chart: lidarr
      version: 14.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v1.0.2.2592
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "music-box"
        hosts:
          - host: &host "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: lidarr-config-v1
      music:
        enabled: true
        mountPath: /music
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media/Music"
            server: "${TRUENAS_ADDR}"
      downloads:
        enabled: true
        mountPath: /downloads
        type: pvc
        existingClaim: downloads
        subPath: complete/music
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 1003
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1G
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
