---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m0s
  values:
    env:
      TZ: "Europe/Rome"
    config:
      lokiAddress: http://${LOKI_ADDR}:3100/loki/api/v1/push
