---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      version: 6.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m0s
  install:
    createNamespace: true
  values:
    env:
      TZ: "${TIMEZONE}"
    config:
      lokiAddress: http://${LOKI_ADDR}:3100/loki/api/v1/push
