---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m0s
  values:
    env:
      TZ: "Europe/Rome"
    config:
      lokiAddress: http://${LOKI_ADDR}:3100/loki/api/v1/push
