---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: storage-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.6.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  interval: 10m0s
  values:
    controller:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
