---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fission
  namespace: fission
spec:
  chart:
    spec:
      chart: fission-all
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: fission
        namespace: flux-system
  interval: 5m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
