---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fission
  namespace: fission
spec:
  chart:
    spec:
      chart: fission-all
      version: v1.19.0
      sourceRef:
        kind: HelmRepository
        name: fission
        namespace: flux-system
  interval: 5m0s
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Service
              name: router
            patch:
              - op: add
                path: /spec/loadBalancerIP
                value: "${SVC_FISSION_ADDR}"
