---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: network-ups-tools
  namespace: kube-system
spec:
  chart:
    spec:
      chart: network-ups-tools
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: ghcr.io/k8s-at-home/network-ups-tools
      tag: v2.7.4-2479-g86a32237
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-ups
                  operator: Exists
    persistence:
      ups:
        enabled: true
        hostPath: /dev/bus/usb/001/003
        mountPath: /dev/bus/usb/001/003
    config:
      files:
        ups.conf: |
          [apc]
            driver = usbhid-ups
            port = auto
            desc = ""
