---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-v1
  namespace: home-cloud
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
