---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/syncthing
              tag: 1.25.0
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 250Mi
        strategy: Recreate
    service:
      main:
        ports:
          http:
            port: 8384
      listen:
        controller: main
        ports:
          listen-tcp:
            port: 22000
            protocol: TCP
          listen-udp:
            port: 22000
            protocol: UDP
      discovery:
        controller: main
        ports:
          discovery:
            port: 21027
            protocol: UDP
    ingress:
      main:
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "sync"
        hosts:
          - host: &host "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: syncthing-tls
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: syncthing-config-v1
        globalMounts:
          - path: /config
