---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/syncthing
              tag: 1.24.0
              pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: 8384
      listen:
        enabled: true
        ports:
          listen-tcp:
            enabled: true
            port: 22000
            protocol: TCP
          listen-udp:
            enabled: true
            port: 22000
            protocol: UDP
      discovery:
        enabled: true
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
    ingress:
      main:
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "sync"
        hosts:
          - host: &host "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: syncthing-tls
    persistence:
      data:
        enabled: true
        mountPath: /config
        type: pvc
        existingClaim: syncthing-config-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi
