---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: home-cloud
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: syncthing
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: syncthing/syncthing
      tag: 1.18.5
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Rome
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "sync"
        hosts:
          - host: "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - "syncthing.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 0.5Gi
        storageClass: longhorn
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi
