---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/samba-in-kubernetes/samba-operator/releases/download/v0.2/samba-operator-v0.2-default.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          control-plane: controller-manager
        name: samba-operator-controller-manager
        namespace: samba-operator-system
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/arch: amd64
