---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.22.1-arm
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: "1,31"
            resources:
              requests:
                cpu: 15m
                memory: 0.5G
              limits:
                # cpu: 500m
                memory: 1G
        strategy: Recreate
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss"
        hosts:
          - host: &host "freshrss.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: freshrss-tls
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: freshrss-data-v1
        globalMounts:
          - path: /var/www/FreshRSS/data
      extensions:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: freshrss-extensions-v1
        globalMounts:
          - path: /var/www/FreshRSS/extensions
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
