---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: rhasspy/wyoming-whisper
      tag: latest
      pullPolicy: Always
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
    args:
      - --model
      - tiny
      - --language
      - en
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_WHISPER_ADDR}"
        ports:
          http:
            port: 10300
            protocol: TCP
    persistence:
      config:
        enabled: true
        mountPath: /data
        type: emptyDir
