---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: rhasspy/wyoming-whisper
      tag: latest
      pullPolicy: Always
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
    args:
      - --model
      - small
      - --language
      - it
    service:
      main:
        ports:
          http:
            enabled: false
          tcp:
            enabled: true
            primary: true
            port: 10300
            protocol: TCP
    persistence:
      config:
        enabled: true
        mountPath: /data
        type: emptyDir
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
