---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: homeassistant/amd64-addon-whisper
      tag: 0.2.0
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          tcp:
            port: 10300
            protocol: TCP
    persistence:
      config:
        enabled: true
        mountPath: /data
        type: configMap
    configMaps:
      config:
        enabled: true
        data:
          model: tiny-int8
          language: it
          beam_size: 1
    nodeSelector:
      kubernetes.io/arch: amd64
