---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data-v1
  namespace: traefik
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
