---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 21.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 5m0s
  values:
    envFrom:
      - secretRef:
          name: provider-secrets
    ingressClass:
      isDefaultClass: false
    persistence:
      enabled: true
      existingClaim: traefik-data-v1
    certResolvers:
      acme:
        caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        email: "${SECRET_EMAIL}"
        dnsChallenge:
          provider: porkbun
        storage: /data/acme.json
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    service:
      externalIPs:
        - "${SVC_TRAEFIK_ADDR}"
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      traefik:
        espose: true
