apiVersion: v1
kind: Secret
metadata:
    name: provider-secrets
    namespace: traefik
type: Opaque
data:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:PerRIm8A4VJPfTjL/iarR5c1ZVkGkfZoU8aGRIpdxSdXaYVezIXiBOv0XXtgSIahAFH08N+zPFQtMibQ2oXKOP9Y1ng=,iv:hSA+fBT16UA0clDsZOFaz/+ni+7vteokUJ/y6W6CLy0=,tag:l95e9NhAtR6u5YZ8Jg1ZGA==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:mkFjqJXnJcGpPf92cpdsSzRqLqkkc4sJO7D4COMDDYqcfuFlpoCReOqOqaVLwSjUJ/mSQAj1hJiHLj2WJadmTZwM4Ws=,iv:6n6K0QanzrNfahhXZayx3Hb1tfqfh1okSy5/CDztgVw=,tag:OzXuEJRwAB1kfYcaQ1SeAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Z29HcU1ZWGJIcTdzb2M3
            RHQzWlBRNXlTZTMxbTlrSElGYlNyNEk3QlJzClRLc3F0TjM4TVE3eHE4a0xOTUhS
            Vlo2Z0RsbmcySHV1TDNlZGZXMUIzbEEKLS0tIGUvdWVzanliUG5DbWNwcVJoaVJj
            eEM0ZnpBdjhEdnlYUFFWWHNqRnJEVEkKIe/YgfmwZFheMJrur72yalBXykW21d1t
            Xkt2OpLNH/46RzxMgCEV7uaZ6IAvCX+yoedCmnkJ9Aa5VO3vC9M4kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T14:53:19Z"
    mac: ENC[AES256_GCM,data:UYAYe6euAGtmowyWlcaN7d5kbF0EVRzWtc78nQwo0eL7PUixKi+tUet5DzAgOb0ey0vL28x5fAEtuiOaO34sMeohudzLceEy1Es+dLSEDJlNcFIcJLgpvsrozvJu6ZV6dqY7t4a34DrJDvtrZLmdOdIrULaaYkcK55lEQWbdbfU=,iv:3hYfnx/2cDHNnybVbqHU/XbJP+PNGLeWpBCaleCEdkc=,tag:Xfu0vctCAZUnqqirBjTgOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
