---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: redis
      version: 19.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    strategy:
      type: Recreate
    architecture: standalone
    clusterDomain: "${SECRET_DOMAIN}"
    global:
      redis:
        password: "${SECRET_REDIS_PASSWORD}"
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
