---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: redis
      version: 18.12.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: bitnami/redis
      tag: 7.2.4-debian-11-r7@sha256:07a8387e6735491720e539c55439a60235ab268bd7da0403d61f7bfb895822c2
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    architecture: standalone
    clusterDomain: "${SECRET_DOMAIN}"
    global:
      redis:
        password: "${SECRET_REDIS_PASSWORD}"
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
