---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: kube-system
spec:
  chart:
    spec:
      chart: goldilocks
      version: 6.1.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.3.3
      pullPolicy: IfNotPresent
    vpa:
      enabled: true
    controller:
      nodeSelector:
        kubernetes.io/arch: amd64
    dashboard:
      enabled: true
      replicaCount: 1
      nodeSelector:
        kubernetes.io/arch: amd64
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - *host
