---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: kube-system
spec:
  chart:
    spec:
      chart: goldilocks
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.11.1
      pullPolicy: IfNotPresent
    vpa:
      enabled: true
    controller:
      nodeSelector:
        kubernetes.io/arch: amd64
    dashboard:
      enabled: true
      replicaCount: 1
      nodeSelector:
        kubernetes.io/arch: amd64
      ingress:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - *host
            secretName: goldilocks-tls
