---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: huginn
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/huginn/huginn
              tag: latest
              pullPolicy: Always
            env:
              TZ: "${TIMEZONE}"
              DATABASE_ADAPTER: postgresql
              DATABASE_HOST: postgresql.infrastructure.svc.cluster.local
              DO_NOT_CREATE_DATABASE: true
            envFrom:
              - secretRef:
                  name: huginn-db
            resources:
              requests:
                memory: 10Mi
                cpu: 10m
              limits:
                memory: 1Gi
            replicas: 0
        strategy: Recreate
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "face-agent"
        hosts:
          - host: &host "huginn.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: huginn-tls
