---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-v1
  namespace: home-cloud
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nextcloud-db-v1
#   namespace: home-cloud
#   annotations:
#     helm.sh/resource-policy: "keep"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: longhorn-static
#   volumeMode: Filesystem
