---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-v1
  namespace: home-cloud
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: nextcloud-data-v1
