---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-db
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: mariadb
      version: 11.1.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: bitnami/mariadb
      tag: 10.6.8-debian-11-r25
      pullPolicy: IfNotPresent
    auth:
      existingSecret: nextcloud-secrets
      database: nextcloud
      username: nextcloud
    primary:
      # Currently no arm64 image (https://github.com/bitnami/bitnami-docker-redis/issues/192)
      nodeSelector:
        kubernetes.io/arch: amd64
      persistence:
        enabled: true
        existingClaim: nextcloud-db-0
      configuration: |-
        [mysqld]
        innodb_file_per_table=1 # https://docs.nextcloud.com/server/24/admin_manual/configuration_database/mysql_4byte_support.html
        skip-name-resolve
        explicit_defaults_for_timestamp
        basedir=/opt/bitnami/mariadb
        plugin_dir=/opt/bitnami/mariadb/plugin
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        tmpdir=/opt/bitnami/mariadb/tmp
        max_allowed_packet=16M
        bind-address=*
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
        log-error=/opt/bitnami/mariadb/logs/mysqld.log
        character-set-server=UTF8
        collation-server=utf8_general_ci
        slow_query_log=0
        slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
        long_query_time=10.0

        [client]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        default-character-set=UTF8
        plugin_dir=/opt/bitnami/mariadb/plugin

        [manager]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      resources:
        # requests:
        #   memory: 100Mi
        #   cpu: 100m
        # limits:
        #   memory: 250Mi
