apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: home-cloud
data:
    username: ENC[AES256_GCM,data:4RbSUrd8Wy+zU1gx,iv:6n3fhIZB6pCWo1S9Hd2pKc7xhIaXnCyKysFTGmw+VpM=,tag:9/EuUZ9ACGZrVIxyGLQnSA==,type:str]
    password: ENC[AES256_GCM,data:NQweVCFh2XCwlm7uSxSfyBGu1O0sworE/PRYMA==,iv:VkyI+TuFzwzn7ad1ubnLqk7I9hN/3dZv05QCecRw7Pc=,tag:hfYvKmQfXQD/ct8vc44DmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZmgwVWRQZElYNE1lMkVD
            Z2Z4eEtjVjVpd1U1RGh2MXc4RTB0VHAyajNVCmJYQytTdE53ajI4cENIK1hhWTg5
            QUwrR2hQZlZ1ZUZPdm9vKzZHdkNtU00KLS0tIGJab1h1RkVaeGJFcFZqSHoxbWJ6
            OGlXcTRKMGxlUytFYTk4ckJLVG5iQ0kKm6yfqyXoDOAvAnXpwORVYH/zbKarlXy7
            UqY9YkKqDAP6z84vptPRaWDB/n8RxQeKGwC896/czwGv1bPKdeg3iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T22:18:29Z"
    mac: ENC[AES256_GCM,data:8lkpJZ8Row1praBNqGEQfHYeK9qUUIlrTwPTyyI8/8eEcj5K4APk59QjaZkQGNHf5gJ99DIxdIw2fpYClW7wkrs/qfy7cxT27pNERrCJXFDIFVvJc1BOs+vGN6LOVK0RrqusjcLthxCC45cOYru1iNGn8HSENKwmjkCYNWftHVg=,iv:Dt7wb3HZJ406LcoSCMb40dRIZwfE2v8PfYxe4/KDrIY=,tag:mIUb2TFd4Yeo6yA0K8C0QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
