---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: nextcloud
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - &host "nextcloud.${SECRET_DOMAIN}"
    nextcloud:
      host: *host
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-user
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: false
      type: mysql
      host: nextcloud-db-mariadb:3306
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secrets
        usernameKey: mariadb-user
        passwordKey: mariadb-password
    persistence:
      enabled: true
      existingClaim: nextcloud-data-v1
    resources:
      # requests:
      #   memory: 100Mi
      #   cpu: 100m
      # limits:
      #   memory: 250Mi
    rbac:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-db
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: mariadb
      version: 11.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: bitnami/mariadb
      tag: 10.6.8-debian-11-r21
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    auth:
      database: nextcloud
      auth:
        username: nextcloud
        existingSecret: nextcloud-db-secrets
    primary:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      persistence:
        enabled: true
        existingClaim: nextcloud-db-v1
      resources:
        # requests:
        #   memory: 100Mi
        #   cpu: 100m
        # limits:
        #   memory: 250Mi
