---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home-cloud
spec:
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: nextcloud
      tag: 23.0.0-apache
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Rome
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
      host: "nextcloud.${SECRET_DOMAIN}"
      path: /
      tlsSecret: "networking/${SECRET_DOMAIN//./-}-tls"
    persistence:
      enabled: true
      retain: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 8Gi
      storageClass: longhorn
      nextcloudData:
        enabled: true
        storageClass: nfs-storage
    nextcloud:
      host: "nextcloud.${SECRET_DOMAIN}"
    internalDatabase:
      enabled: false
    mariadb:
      enabled: true
      auth:
        password: 'changeme'
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    # resources:
    #   requests:
    #     memory: 100Mi
    #     cpu: 100m
    #   limits:
    #     memory: 250Mi
