---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: nextcloud
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      servicePort: https
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - &host "nextcloud.${SECRET_DOMAIN}"
    nextcloud:
      host: *host
      # existingSecret:
      #   enabled: true
      #   secretName: nextcloud-secrets
      #   usernameKey: nextcloud-user
      #   passwordKey: nextcloud-password
    cronjob:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nextcloud-data-v1
    phpClientHttpsFix:
      enabled: true
      protocol: https
    resources:
      # requests:
      #   memory: 100Mi
      #   cpu: 100m
      # limits:
    #   #   memory: 250Mi
    # rbac:
    #   enabled: true
    # internalDatabase:
    #   enabled: false
    # externalDatabase:
    #   existingSecret:
    #     secretName: nextcloud-secrets
    #     usernameKey: mariadb-user
    #     passwordKey: mariadb-password
    # mariadb:
    #   enabled: true
    #   auth:
    #     existingSecret: nextcloud-secrets
    #     database: nextcloud
    #     username: nextcloud
    #   common:
    #     affinities:
    #       nodes:
    #         requiredDuringSchedulingIgnoredDuringExecution:
    #           nodeSelectorTerms:
    #             - matchExpressions:
    #                 - key: beta.kubernetes.io/arch
    #                   operator: In
    #                   values:
    #                     - amd64
    #   primary:
    #     persistence:
    #       enabled: true
    #       existingClaim: nextcloud-db-v1
    #     resources:
    #       # requests:
    #       #   memory: 100Mi
    #       #   cpu: 100m
    #       # limits:
    #       #   memory: 250Mi
