---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 3.5.14
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: nextcloud
      tag: 26.0.2-fpm # or 25.0.7-fpm-alpine
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      tls:
        - hosts:
            - &host "nextcloud.${SECRET_DOMAIN}"
          secretName: nextcloud-tls
    cronjob:
      enabled: true
    nextcloud:
      host: *host
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
      extraEnv:
        - name: REDIS_HOST
          value: redis-master.infrastructure.svc.cluster.local
        - name: REDIS_HOST_PASSWORD
          value: "${SECRET_REDIS_PASSWORD}"
      mail:
        enabled: true
        fromAddress: "${SECRET_EMAIL_USER}"
        domain: "${SECRET_EMAIL_DOMAIN}"
        smtp:
          host: "${SECRET_EMAIL_SERVER}"
          secure: ssl
          port: 465
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql.infrastructure.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: username
        passwordKey: password
    persistence:
      enabled: true
      existingClaim: nextcloud-config-v1
      accessMode: ReadWriteMany
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data-v1
        accessMode: ReadWriteMany
    metrics:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 0.5Gi
      limits:
        cpu: 2
        memory: 4Gi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
