---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: nextcloud
      tag: 27.0.2-fpm # or 25.0.7-fpm-alpine
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      tls:
        - hosts:
            - &host "nextcloud.${SECRET_DOMAIN}"
          secretName: nextcloud-tls
    cronjob:
      enabled: true
    nextcloud:
      host: *host
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
      extraEnv:
        - name: REDIS_HOST
          value: redis-master.infrastructure.svc.cluster.local
        - name: REDIS_HOST_PASSWORD
          value: "${SECRET_REDIS_PASSWORD}"
      extraVolumes:
        - name: cronjobs-config
          configMap:
            name: nextcloud-cronjobs-config
            items:
              - key: www-data
                path: www-data
        - name: php-fpm-config
          configMap:
            name: nextcloud-php-fpm-config
            items:
              - key: zz-www.conf
                path: zz-www.conf
      extraVolumeMounts:
        - name: cronjobs-config
          mountPath: /var/spool/cron/crontabs/www-data
          subPath: www-data
        - name: php-fpm-config
          mountPath: /usr/local/etc/php-fpm.d/zz-www.conf
          subPath: zz-www.conf
      mail:
        enabled: true
        fromAddress: "${SECRET_EMAIL_USER}"
        domain: "${SECRET_EMAIL_DOMAIN}"
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
        previews.config.php: |-
          <?php
          $CONFIG = array(
            'enabledPreviewProviders' =>
              array (
                'OC\Preview\AVI',
                'OC\Preview\BMP',
                'OC\Preview\GIF',
                'OC\Preview\HEIC',
                'OC\Preview\JPEG',
                'OC\Preview\MarkDown',
                'OC\Preview\MKV',
                'OC\Preview\Movie',
                'OC\Preview\MP3',
                'OC\Preview\MP4',
                'OC\Preview\PDF',
                'OC\Preview\PNG',
                'OC\Preview\TXT',
                'OC\Preview\XBitmap',
              ),
          );
        custom.config.php: |-
          <?php
          $CONFIG = array(
            'default_phone_region' => 'IT',
          );
    nginx:
      enabled: true
    deploymentAnnotations:
      configmap.reloader.stataker.com/reload: "nextcloud-php-fpm-config"
      secret.reloader.stataker.com/reload: "nextcloud,nextcloud-db"
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql.infrastructure.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: username
        passwordKey: password
    persistence:
      enabled: true
      existingClaim: nextcloud-config-v1
      accessMode: ReadWriteMany
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data-v1
        accessMode: ReadWriteMany
    metrics:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 0.5Gi
      limits:
        cpu: 4
        memory: 4Gi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
