---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: nextcloud
      flavor: apache
      image: apache-24.0.3
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;

          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      servicePort: https
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - &host "nextcloud.${SECRET_DOMAIN}"
    nextcloud:
      host: *host
      # existingSecret:
      #   enabled: true
      #   secretName: nextcloud-secrets
      #   usernameKey: nextcloud-user
      #   passwordKey: nextcloud-password
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
    cronjob:
      enabled: true
      image:
        repository: curlimages/curl
        tag: 7.84.0
      curlInsecure: true
    persistence:
      enabled: true
      existingClaim: nextcloud-data-v1
    phpClientHttpsFix:
      enabled: true
      protocol: https
    resources:
      # requests:
      #   memory: 100Mi
      #   cpu: 100m
      # limits:
    #   #   memory: 250Mi
    # rbac:
    #   enabled: true
    # internalDatabase:
    #   enabled: false
    # externalDatabase:
    #   existingSecret:
    #     secretName: nextcloud-secrets
    #     usernameKey: mariadb-user
    #     passwordKey: mariadb-password
    # mariadb:
    #   enabled: true
    #   auth:
    #     existingSecret: nextcloud-secrets
    #     database: nextcloud
    #     username: nextcloud
    #   common:
    #     affinities:
    #       nodes:
    #         requiredDuringSchedulingIgnoredDuringExecution:
    #           nodeSelectorTerms:
    #             - matchExpressions:
    #                 - key: beta.kubernetes.io/arch
    #                   operator: In
    #                   values:
    #                     - amd64
    #   primary:
    #     persistence:
    #       enabled: true
    #       existingClaim: nextcloud-db-v1
    #     resources:
    #       # requests:
    #       #   memory: 100Mi
    #       #   cpu: 100m
    #       # limits:
    #       #   memory: 250Mi
