---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-fpm-config
  namespace: home-cloud
data:
  # The helm chart doesn't currently support tweaking these values, so we use a
  # custom mount. The files are mounted alphabetically, so to make sure we are
  # the last override, let's use zz-www.conf as filename.
  # References:
  # - https://docs.nextcloud.com/server/16/admin_manual/installation/server_tuning.html#tune-php-fpm
  # - https://spot13.com/pmcalculator/
  zz-www.conf: |
    [www]
    pm = dynamic
    pm.max_children = 120
    pm.start_servers = 12
    pm.min_spare_servers = 6
    pm.max_spare_servers = 50
