apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: home-cloud
data:
    nextcloud-user: ENC[AES256_GCM,data:naiyYrGl9+nchkDj,iv:6klGLHsP5sCCOaHO5jZ2R3F5fFr34VcITs44UxTEsYw=,tag:YFYV/Zzt8JFn39VtfhBM4Q==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:eZ8eS4/b7YS9KwZnQtRdpv3uQwVGBe9ZevuYUCkDqbfX2Dep83JhcbqR5/mjCe6C9xamxoR2Zj4=,iv:GV++LrqGv3q07jINXtB7YZhTBQx+v6Urj7+br7435jM=,tag:O1DpthL/oYpv3jcNULHygw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:3hu1/g0w0OlxjVDimg04nlpaxDydD+rw9Eencw==,iv:sR+AoSIsuStfwPG1Xt8Y6bpISz3qAIENOwFc4W/SI50=,tag:1NRasanqIuuWJZv+SMz3Xg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:vM1P2qBqfPkn2Mub52F+jqczDMJMNdAy0PGe4A==,iv:8nC4rI+zGCLLH0v2PljSPG1T2/NGzX9mTaUvdtQC4Bc=,tag:DXdz+Z/bmm9lf+v879QuCg==,type:str]
    mariadb-user: ENC[AES256_GCM,data:Z1hSuVbPCH75s2kL,iv:Weh+UW1TD+v6ZvHHTvMNfDczl+BEjHXxYGhZRJxxBFE=,tag:yhdc1C1fCwWOCbDyGFGCOA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:XFNqkDy/kC82yvBil3YvX6mZzqRcX9Dx8LqhwQ==,iv:kUi18ow4SdYsp53ERKKqSoxEAQ0C9UOYcZ9GwCX5Kf4=,tag:ceHZ8yMP5WuTDSW9j3JkQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydEduUjJvYWVRUHdOT1BM
            d0hyVFZtMjdqWW1aS2krckp6a0F1M0djTHlJCjJpZm5rNFJQa0k3Tm80VTh6Z3Iw
            SGlqWkJvY2s0UFdJNTFUa1M1QjVvOE0KLS0tIDlWZ0l5YVZaU1l6UWVoaVh6ZTlY
            dytYYkZkSzZhUHBnY0syeGc2czA4K0UK41KBkbCOl7dQfaQvSmw8pZaJlJRuGhE8
            0pPQquhaLfkDga/3jGDLLmMEZr09z25DsZbdQp6Q9JfMBiSZmolDJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-03T06:06:47Z"
    mac: ENC[AES256_GCM,data:rVeT6KdECdleewIry26CvPif5eDt3UY8ZcxD76EHdjVtuhI8lXX6PypKJ8GnjkM1b6fAg4JoQAsv9ZBvCpQSHK61UHHorN1Ef1Up+PQZfE1/dSFDZ4dLZ/e7cqfWs+c0RiQIGsz5FrbyVSYar6NzF1oS/BrkPdQs/Jo3f4XHIRc=,iv:td/sDrwBJA5xXlZAEsZr3JueOoMjgjYfsTFl2k1HchA=,tag:GUBckQ+nBQccVw8eTaJAlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
