---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
spec:
  chart:
    spec:
      chart: gpu-device-plugin
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 5m0s
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
