---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: mongodb
      version: 15.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    strategy:
      type: Recreate
    architecture: standalone
    useStatefulSet: true
    clusterDomain: "${SECRET_DOMAIN}"
    auth:
      rootUser: root
      rootPassword: "${SECRET_MONGODB_PASSWORD}"
    persistence:
      enabled: true
      existingClaim: mongodb-primary-v1
    service:
      type: LoadBalancer
      loadBalancerIP: "${SVC_MONGODB_ADDR}"
    diagnosticMode: # All probes will be disabled and the command will be overridden with sleep infinity
      enabled: false
    backup:
      enabled: true
      cronjob:
        schedule: "@daily"
        storage:
          existingClaim: mongodb-backups-v1
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      # limits:
      #   memory: 100Mi
      #   cpu: 100m
    nodeSelector:
      kubernetes.io/arch: amd64
