---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: networking
spec:
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts
      chart: reflector
      version: 6.1.47
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 5m0s
