---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.1.0
  interval: 10m0s
  values:
    env:
      TZ: Europe/Rome
    service:
      main:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: longhorn
      media:
        enabled: true
        mountPath: /data
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/user/media"
            server: "${UNRAID_ADDR}"
      transcode:
        enabled: true
        type: emptyDir
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        cpu: 1000m
        memory: 250Mi
      limits:
        memory: 1000Mi
