---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      version: 6.3.4
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.27.2.5929-a806c5905
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    hostNetwork: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_PLEX_ADDR}"
        ports:
          http:
            port: 32400
          gdm-discovery-1:
            enabled: true
            port: 32410
            protocol: UDP
            targetPort: 32410
          gdm-discovery-2:
            enabled: true
            port: 32412
            protocol: UDP
            targetPort: 32412
          gdm-discovery-3:
            enabled: true
            port: 32413
            protocol: UDP
            targetPort: 32413
          gdm-discovery-4:
            enabled: true
            port: 32414
            protocol: UDP
            targetPort: 32414
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "plex"
          nginx.ingress.kubernetes.io/app-root: "/web" # Redirect / -> /web
        hosts:
          - host: &host "music.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: plex-config-v1
      media:
        enabled: true
        mountPath: /media
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media"
            server: "${TRUENAS_ADDR}"
      transcode:
        enabled: true
        type: emptyDir
    podSecurityContext:
      # Hardware acceleration using an Intel iGPU w/ QuickSync
      # These IDs below should be matched to your `video` and `render` group on the host
      # To obtain those IDs run the following grep statement on the host:
      # $ cat /etc/group | grep "video\|render"
      # video:x:44:
      # render:x:109:
      supplementalGroups:
        - 44
        - 109
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        cpu: 100m
        memory: 0.5G
      limits:
        cpu: 1000m
        memory: 1G
