---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/plex
              tag: 1.40.1
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              PUID: 568
              PGID: 1003
            resources:
              requests:
                cpu: 100m
                memory: 0.5G
              limits:
                # cpu: 1000m
                memory: 1G
        strategy: Recreate
    service:
      main:
        controller: main
        ports:
          http:
            port: 32400
            protocol: HTTP
          dlna:
            port: 1900
            protocol: UDP
          gdm-discovery-1:
            port: 32410
            protocol: UDP
          gdm-discovery-2:
            port: 32412
            protocol: UDP
          gdm-discovery-3:
            port: 32413
            protocol: UDP
          gdm-discovery-4:
            port: 32414
            protocol: UDP
          dlna-plex:
            port: 32469
            protocol: TCP
    ingress:
      internal:
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "plex"
          nginx.ingress.kubernetes.io/app-root: "/web" # Redirect / -> /web
        labels:
          nginx.ingress.kubernetes.io/validation: "skip" # Custom label to skip duplicate host/path validation (split horizon dns)
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: plex-tls
      public:
        className: "nginx-public"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/app-root: "/web" # Redirect / -> /web
        labels:
          nginx.ingress.kubernetes.io/validation: "skip" # Custom label to skip duplicate host/path validation (split horizon dns)
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: plex-tls
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: plex-config-v1
        globalMounts:
          - path: /config
      media:
        enabled: true
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        globalMounts:
          - path: /media
      transcode:
        enabled: true
        type: emptyDir
      intel:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
    defaultPodOptions:
      hostNetwork: true
      securityContext:
        # Hardware acceleration using an Intel iGPU w/ QuickSync
        # These IDs below should be matched to your `video` and `render` group on the host
        # To obtain those IDs run the following grep statement on the host:
        # $ cat /etc/group | grep "video\|render"
        # video:x:44:
        # render:x:109:
        supplementalGroups:
          - 44
          - 109
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/custom-intel-gpu
                    operator: In
                    values:
                      - "true"
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
