---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    controller:
      replicas: 1
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.26.0.5715-8cf78dab3
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Rome
    hostNetwork: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "plex"
          nginx.ingress.kubernetes.io/app-root: "/web" # Redirect / -> /web
        hosts:
          - host: "music.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "music.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: plex-config-v1
      media:
        enabled: true
        mountPath: /media
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media"
            server: "${TRUENAS_ADDR}"
      transcode:
        enabled: true
        type: emptyDir
    podSecurityContext:
      # Hardware acceleration using an Intel iGPU w/ QuickSync
      # These IDs below should be matched to your `video` and `render` group on the host
      # To obtain those IDs run the following grep statement on the host:
      # $ cat /etc/group | grep "video\|render"
      # video:x:44:
      # render:x:109:
      supplementalGroups:
        - 44
        - 109
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
