---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: lscr.io/linuxserver/radarr
      tag: 4.7.5
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 568
      PGID: 1003
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "filmstrip"
          hajimari.io/info: "Movies"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: radarr-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        type: pvc
        existingClaim: radarr-config-v1
      movies:
        enabled: true
        mountPath: /movies
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        subPath: Movies
      downloads:
        enabled: true
        mountPath: /downloads
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/downloads
        subPath: complete/movies
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1G
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
