---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  GATEWAY_ADDR: "10.17.1.1"
  KUBE_MASTER_ADDR: "10.17.1.24"
  TRUENAS_ADDR: "10.17.1.15"
  NETWORK_METALB_CIDR: "10.17.2.0/24"
  LANCACHE_ADDR: "10.17.2.32"
