apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
data:
    SECRET_ALERT_MANAGER_WEBHOOK: ENC[AES256_GCM,data:f/ZtNC0b9xRL4htOTwg+GgQXuxYe5yP9LNTb2QR2v7Qr6xPMtBThHXSZ5Lu0cuWFQEBdcozS8aEXVYqHM2dZKMs4tJLdg0mMQu64xVoa5sHaHluKeTGTHDU23ReLXbv74+YIgXF/l1RwQ7QmmUCOkIixMqegsCjCV3iav+ZiaQdd3n7/1B2CRcjOmWQ9PbMoh2ILN/rDoLmbzvO6TZofsSZkCi8=,iv:r0G1fOmVcoXiDVyJyd3BG6ujv83C0xSLZ7ffitZ5XO0=,tag:KbzhgFPdm+/Djk8WKRM6zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-26T22:56:35Z"
    mac: ENC[AES256_GCM,data:1QyZ8U7lqE9R0+ebTSVHSZD/34kxPLrYD4dQB0UZQMOlW4WmaYCsiCnGCgzGua9+4lDJopxhHi76pdjZBpLjUqEnZaMcW+T9bVCn37zPZolXMJDqChyzmMIPQKlvXthNFz5drIw5QYMus5Xol1s1Ru7QULrwXij8SBp6lVHmyP0=,iv:KcN5DumU2BOQZxZ3vXTMazpKiUKpVmxuwgiaS8hM12Q=,tag:P/F1eE/w/TyJJBrSLqq84Q==,type:str]
    pgp:
        - created_at: "2021-11-26T22:56:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7EApPiAMpK+AQ//URUwo6/5z0pAq172V83wTL2fyrg0P/+9XbxKliZNgPKe
            aSdeomUPVYBu1lCWDOeTPtGPMfU1VD1mpyuguwyWoFGtcs7ZvXQ2emeciJtsuENr
            pXalS4TGNikmXuwKf2Cp0Vy9BfR35/w43MBxJ+ynWQX7u9mt77V2KjhYhifHjl1D
            lOHZtlb0yT8xZFvLAf3ZDE/C/BClIWeeMhksFOhORN0P9v6RvnazpXa61aEUq3Zk
            WUkUv6uTUqn7ryjBpeyegvZyNgBG85EJmF0attWryAM4w2bHDdx+uOgDDefYkjs2
            2iZKJxPSAQhkkDwvXvweZwqqbZ74CGfhMc1pMv3yrlh9loxGCrqMMu55O5VSnCbM
            Bg4x57SlI8HCbJjtdTP/OWuLBQKRgqPZipEQCgDBFDR9mc8HjnHquTXFpCjZGWLO
            eMd76GoOqj9YCMEFbkkY2vceJf5gYCZXlhYVSZ+LzVpCHwXz6mvB/rC9J1rzwWna
            5WZAbX3/qxJcMumVUCE8ryBoi/0j8cDYBCk4TtNoE6A8XuodJSvY+81op8zaam+S
            bGX+vv5arGlAcs3G5BNrNwttr+Jlab83HzkacxxT8Eo7ukadYOzP9i4dJyymgyJT
            XKSLIqpc6fxnl3I3+3EzUGMfkMtTVD4vMEgaQBoECrrx2xcCsqKpBKmLewlCK7DS
            XgGi81M1OyF1pXG7HdiXGeFfxqzf0lpiEqjKDHwoldZrdhivL402Hh19Pnp1FL+F
            /wgaCujkoIBYVl5+99BmwML1zZU/nGCL2J5izsaYYa9sZVzaOf8Uf7+Me9k3zgU=
            =Jozn
            -----END PGP MESSAGE-----
          fp: 3A058E887D32F660D24E13244916F5AB66E13FEF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
