---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media-v1
  namespace: home-cloud
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
