---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: vabene1111/recipes
      tag: 1.5.6
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      ENABLE_PDF_EXPORT: "1"
    envFrom:
      - secretRef:
          name: tandoor-db
    service:
      main:
        ports:
          http:
            port: 8080
          static:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chef-hat"
        hosts:
          - host: &host "tandoor.${SECRET_DOMAIN}"
            paths:
              - path: /
              - path: /static
                service:
                  port: 80
              - path: /media
                service:
                  port: 80
        tls:
          - hosts:
              - *host
            secretName: tandoor-tls
    persistence:
      config:
        enabled: false
      media:
        enabled: true
        mountPath: /opt/recipes/mediafiles
        type: pvc
        existingClaim: tandoor-media-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi
