---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: vabene1111/recipes
              tag: 1.5.16
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              ENABLE_PDF_EXPORT: "1"
            envFrom:
              - secretRef:
                  name: tandoor-db
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 250Mi
        strategy: Recreate
    service:
      main:
        ports:
          http:
            port: 8080
          static:
            port: 80
    ingress:
      main:
        enabled: true
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chef-hat"
        hosts:
          - host: &host "tandoor.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
              - path: /static
                service:
                  name: main
                  port: static
              - path: /media
                service:
                  name: main
                  port: static
        tls:
          - hosts:
              - *host
            secretName: tandoor-tls
    persistence:
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: tandoor-media-v1
        globalMounts:
          - path: /opt/recipes/mediafiles
