---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v1
  namespace: media
  labels:
    recurring-job-group.longhorn.io/backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
