---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: prowlarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 4.1.0
  interval: 10m0s
  values:
    env:
      TZ: Europe/Rome
    service:
      main:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
