---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: linuxserver/prowlarr
      tag: 1.8.1259
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 568
      PGID: 1003
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "cloud-search"
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: prowlarr-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        type: pvc
        existingClaim: prowlarr-config-v1
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1G
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
