---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-static
  namespace: longhorn-system
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  # fromBackup: ""
  fsType: "ext4"
