---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: browserless
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/browserless/chrome
              tag: latest
              pullPolicy: Always
            env:
              TZ: "${TIMEZONE}"
              MAX_CONCURRENT_SESSIONS: 2
            resources:
              requests:
                memory: 10Mi
                cpu: 10m
              limits:
                memory: 1Gi
            replicas: 0
        strategy: Recreate
    service:
      main:
        ports:
          http:
            port: 3000
