---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn
  volumeMode: Filesystem
