---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://utkuozdemir.org/helm-charts
      chart: filebrowser
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir
        namespace: flux-system
  interval: 10m0s
  values:
    config:
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      # annotations:
      #   hajimari.io/enable: "true"
      #   hajimari.io/group: "media"
      #   hajimari.io/icon: "subtitles"
      hosts:
        - host: "downloads.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "bazarr.${SECRET_DOMAIN}"
    rootDir:
      retain: true
      type: pvc
      pvc:
        accessMode: ReadWriteOnce
        existingClaim: downloads
        storageClassName: longhorn
    db:
      retain: true
      type: pvc
      pvc:
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClassName: longhorn
    podSecurityContext:
      fsGroup: 1003
      fsGroupChangePolicy: "OnRootMismatch"
    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 477M
    #   limits:
    #     # cpu: 500m
    #     memory: 799M
