---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  chart:
    spec:
      chart: filebrowser
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir
        namespace: flux-system
  interval: 10m0s
  values:
    ingress:
      enabled: true
      className: "nginx"
      # annotations:
      #   hajimari.io/enable: "true"
      #   hajimari.io/group: "media"
      #   hajimari.io/icon: "subtitles"
      hosts:
        - host: &host "downloads.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    service:
      port: 8080
    rootDir:
      type: pvc
      pvc:
        existingClaim: downloads
    db:
      type: pvc
      pvc:
        existingClaim: filebrowser-db-v1
    podSecurityContext:
      fsGroup: 1003
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 15m
        memory: 100M
      limits:
        # cpu: 500m
        memory: 0.5G
