---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-v1
  namespace: media
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pv-downloads
  storageClassName: smb
