---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: 3.0.10
              pullPolicy: IfNotPresent
            probes:
              liveness:
                spec:
                  timeoutSeconds: 2
              readiness:
                spec:
                  timeoutSeconds: 2
              startup:
                spec:
                  timeoutSeconds: 2
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 568
      PGID: 1003
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "television-box"
          hajimari.io/info: "TV Shows"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sonarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: sonarr-config-v1
        globalMounts:
          - path: /config
      tv:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: "/mnt/tank/media"
        globalMounts:
          - path: /tv
        advancedMounts:
          main:
            main:
              - subPath: "TV Shows"
      downloads:
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: "/mnt/tank/downloads"
        globalMounts:
          - path: /downloads
        advancedMounts:
          main:
            main:
              - subPath: "complete/tv"
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1.5G
