---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: lscr.io/linuxserver/sonarr
      tag: 3.0.10
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 568
      PGID: 1003
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "television-box"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sonarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: sonarr-config-v1
        mountPath: /config
      tv:
        enabled: true
        mountPath: /tv
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media/TV Shows"
            server: "${TRUENAS_ADDR}"
      downloads:
        enabled: true
        mountPath: /downloads
        type: pvc
        existingClaim: sonarr-downloads
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1.5G
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
