---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 10m0s
  values:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "harddisk"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tlsSecret: "networking/${SECRET_DOMAIN//./-}-tls"
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      backupTarget: s3://longhorn@eu/backups
      backupTargetCredentialSecret: minio-secret
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      defaultReplicaCount: 1
      orphanAutoDeletion: "true"
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    annotations:
      configmap.reloader.stakater.com/reload: longhorn-default-setting
    # Remove when back to multinode
    longhornUI:
      replicas: 1
    longhornConversionWebhook:
      replicas: 1
    longhornAdmissionWebhook:
      replicas: 1
