---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 10m0s
  values:
    ingress:
      enabled: true
      ingressClassName: "nginx-internal"
      annotations:
        hajimari.io/appName: "longhorn"
        hajimari.io/enable: "true"
        hajimari.io/group: "admin"
        hajimari.io/icon: "harddisk"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tlsSecret: "networking/${SECRET_DOMAIN//./-}-tls"
    persistence:
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    defaultSettings:
      backupTarget: nfs://${TRUENAS_ADDR}:/mnt/tank/longhorn-backups
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      concurrentReplicaRebuildPerNodeLimit: 2
      defaultReplicaCount: 2
      node-drain-policy: allow-if-replica-is-stopped
      orphanAutoDeletion: "true"
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      restoreVolumeRecurringJobs: true
    annotations:
      configmap.reloader.stakater.com/reload: longhorn-default-setting
