---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 10m0s
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "harddisk"
        hosts:
          - host: "longhorn.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - "longhorn.${SECRET_DOMAIN}"
    persistence:
      defaultClassReplicaCount: 2
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    defaultSettings:
      backupTarget: s3://longhorn@eu/backups
      backupTargetCredentialSecret: minio-secret
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
    annotations:
      configmap.reloader.stakater.com/reload: longhorn-default-setting
