apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: longhorn-system
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:W98jx0wXRhVxc9gTd5ocfiTX4sNuqqpojXPt9Q==,iv:Sm5iMgycVSv+zqW7YhAGT5/S0uCnz8Fxo4JmKa6M0KY=,tag:rSIBKDCHIp5Lx2szSZOB4w==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:AoyJlVy0gIF29FPagk9WzG/FTTykX0iUUvtRc41rYPaaWfxkvBSekXMWTy0pr9nv58JR1Q==,iv:/kISmCuj2VVRxmRKaCLWXHU+y3KfDHl/naAdho4cDYQ=,tag:hJAHueQ9Tc/an61jV+uRMw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ATTvi/bYyezCAUwdPzdqr3+fLBQP5M6cxyJWSgfhHldzvQtF5vWUtKIf78uSHCldLChgHOD3u4I=,iv:tfs3LsbHjeOxuYgevULmjcf3gprcyar4sr0YZJOwakk=,tag:Urt5GOH1OR/PlPgom1BPzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMEY0TElOMHdvWDFITzNt
            VGU2by8xM0JSVFc1SnRPVkRiakhiSjB3Tm1JCkxQNXlPeXNVbk1yOFYxbHBBaDBK
            K25hVGRIQnp1UGY5SVZ1Wm83YUR0aHcKLS0tIHIwaWwvWC9HTnFRM1hNc2VqcmdS
            QWN5R3E2aC9sbUN0QkMyenloL2tFdVkKvYyfrFt5dBnqMkjOr4nhuN0ZF6fxzMHZ
            SfYAn2kGkY8oAF42DHQSs7Fdmg6nwl8dLJwc0gME8zpElad7+yMFOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-20T20:08:08Z"
    mac: ENC[AES256_GCM,data:ULNvrAvesoklpgt0THXUwfhPwPShcghrp25WXLlfjUSbv98B9Qrw9j3rOcB5duMWpOm95q1hr0yNYTWrJUghTzhda4gQsN5ZXvBkqzliIHY1yuCywgSPxYzOyoxB6fTlkM35PSodjEufETyTGavf/tgt4tdb7pLwPxjzhEqNfow=,iv:EeRhC/Wav99ogIwU7z+uQPORYH9RwttUi5iESkJgCuE=,tag:43lSHK2PT5fCAenLA9hvRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
