apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZdRFpUnchfi4xdBrD6vWvlJ/LxIsiqYxEHtjIg==,iv:qb9SR64LeJHEJHgicPzURpWjnH7eseS4qaJVuAKf934=,tag:Y0Hqs9t2Z2ovFlv5toxSDQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:N81D9Xhl5vnnxb/R9oGwHYZQulTJfTXC925jBnsXvjF5IyE/8Ep4ThFv7k44DAlZarUOow==,iv:p7lAP+t67PPu7gb3CTLqS+MK7D9Ld+J+5cJ2uxCIj5A=,tag:wKVhuGR35lrJoU2nVcqcpg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UXz1IrZmyuqPJlC67sV0oVfHDy4YST8r2c9EUvMHcuQLJ3feePdGtg1nhWRzHgq9zwzLZbnPMog=,iv:VBpXfVmM+Z91PQV3Ip8WydbL4Bnf5fWm/Yq1XASepQM=,tag:S9Xp8e6phFXH3wt7ffQEAA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-secret
    namespace: longhorn-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-02T01:17:08Z"
    mac: ENC[AES256_GCM,data:hA1yP24wwqWVoEScnt81JvANazbsyWNFwRLdru8w8LFv13+0mFWimtOdYBBV/kjlpGKbY0hiH62YFL2I5+6tOuC+4iKSZg/JLUcM1W1vJuOenuMU3yaw9l5d5FRHN6dQuu7XxcII7HJyLUy2/troR+h/JJg/IqmlWgk3Xx5TMGo=,iv:GaMe9o8tmVhRbV/mYYhkvEAoN/oFElaUctYjS5YwtGE=,tag:dwzcCjV9sgffkBO2kKCSsQ==,type:str]
    pgp:
        - created_at: "2021-11-23T23:22:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7EApPiAMpK+AQ//f8D8RDLOW4cS3qDaf+ccrBUKuf5pWS2mqAbqiJ0xQzMh
            q7kVDkooJfhSFh+MiW0Lw9ffTdc117Jtgb7HahM8k6Yjwtv+vvYxGUnveaIrehqt
            asqahkgXFSP8WZS0ZF6HmwZ0VosYHZ97fOHehasB5+DeWrdvt4UDxDsZpE7sGodY
            CEQzVsvCrkwYi+uuNW0PA2uiUgCiQ1eeCYFou4MV7+NeY1IYqC3OavdZf1ofBBWd
            PBk628vTnboO31jVIfQ9ZuqEYmP+Va25pTh3r1z0dkai+msveGDIMZp+nUrXY3x5
            6tvVMESEW8rEyA0hdIVm65RxNf1qnxqTid2j5fE1ASLM35nlFNiBFdRPO8IDcLkK
            CKRE2aU2CSZVgcqDX1pSZEKroJ7jmPee0FGJVr2TxyaEey6ZBrjVtsv9ZV3Ldmya
            TInseScnHlMVl+xAnuVK74bKbM5DYbwKnxW+pHjw7W3d8vBeN2z1SLFhCkGJxnSA
            6bJ0MWRQWnxe4SEyvt9xK/TM4XOmjRxDtkHSS54efx0SFd2fykWVMgGaUSaq7JY0
            RYOu7THZEKZf3VtdqlRBCKeqcA+J7Fh0SmjdzSojabGjjiWrSS0lFfpOr2slXudP
            tX5ZmNPUBLteXMsdwi7zZWtYC6X7fz7SHwq8Gxt/dRkmcZ3pCJOaaU7xf6/doCjS
            XgHGSko0bZmBxSTHGs8B+M56OPeF6nbAZFgJq706E5EDHmGBBvtabcOYnJUduxVp
            XPi6Lg0F7cWp5LiZvXfP146vhJhfPS8H8WTsdki2KgUG6S9b3c/3zh63mGCn+JE=
            =q/dq
            -----END PGP MESSAGE-----
          fp: 3A058E887D32F660D24E13244916F5AB66E13FEF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
