---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home-cloud
spec:
  externalIPs:
    - "${HOMEASSISTANT_ADDR}"
  ports:
  - name: http
    port: 8123
    targetPort: 8123
