---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  interval: 5m0s
  values:
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: "nfd-worker-conf"
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      config:
        core:
          labelSources:
            - all
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: "zigbee"
              labels:
                "feature.node.kubernetes.io/zigbee": "true"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class: {op: In, value: ["02"]}
                    vendor: {op: In, value: ["1cf1"]}
                    device: {op: In, value: ["0030"]}
            - name: "intel-gpu"
              labels:
                "feature.node.kubernetes.io/intel-gpu": "true"
              matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    class: {op: In, value: ["0300"]}
                    vendor: {op: In, value: ["8086"]}
            - name: "ups"
              labels:
                "feature.node.kubernetes.io/ups": "apc-usb"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class: {op: In, value: ["03"]}
                    vendor: {op: In, value: ["051d"]}
                    device: {op: In, value: ["0003"]}
