---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
      version: 0.9.0
  interval: 5m0s
  values:
    worker:
      # annotations:
      #   configmap.reloader.stakater.com/reload: "nfd-worker-conf"
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      config: |-
        core:
          sources:
          - custom
          - pci
          - usb
        sources:
          usb:
            deviceClassWhitelist:
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
            deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
          custom:
          - name: "zigbee"
            matchOn:
            - usbId:
                class: ["02"]
                vendor: ["1cf1"]
                device: ["0030"]
          - name: "intel-gpu"
            matchOn:
            - pciId:
                class: ["0300"]
                vendor: ["8086"]
