---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  interval: 5m0s
  values:
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: "nfd-worker-conf"
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      config:
        core:
          labelSources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: "zigbee"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["1cf1"]
                    device: ["0030"]
            - name: "intel-gpu"
              labels:
                - intel-gpu: "true"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: "ups"
              labels:
                - ups: "apc-usb"
              matchOn:
                - usbId:
                    class: ["03"]
                    vendor: ["051d"]
                    device: ["0003"]
