---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  interval: 5m0s
  values:
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: "nfd-worker-conf"
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: "zigbee"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["1cf1"]
                    device: ["0030"]
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
