---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: networking
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m0s
  values:
    tcp:
      "5514": "infrastructure/unifi:syslog"
      "6789": "infrastructure/unifi:mobile-test"
      "8080": "infrastructure/unifi:device-comms"
      "22000": "home-cloud/syncthing-listen:listen-tcp"
      "10200": "home-cloud/piper:tcp"
      "10300": "home-cloud/whisper:tcp"
      "32469": "media/plex:dlna-plex"
      "51413": "media/transmission:utp-tcp"
    udp:
      "1900": "infrastructure/unifi:l2-discovery"
      "3478": "infrastructure/unifi:stun"
      "10001": "infrastructure/unifi:ap-discovery"
      "21027": "home-cloud/syncthing-discovery:discovery"
      "22000": "home-cloud/syncthing-listen:listen-udp"
      # "1900": "media/plex:dlna"
      "32410": "media/plex:gdm-discovery-1"
      "32412": "media/plex:gdm-discovery-2"
      "32413": "media/plex:gdm-discovery-3"
      "32414": "media/plex:gdm-discovery-4"
      "51413": "media/transmission:utp-udp"
    controller:
      containerPort:
        piper-10200: 10200
        plex-1900: 1900
        plex-32410: 32410
        plex-32412: 32412
        plex-32413: 32413
        plex-32414: 32414
        plex-32469: 32469
        syncthing-disc: 21027
        syncthing-tcp: 22000
        syncthing-udp: 22000
        transm-tcp: 51413
        transm-udp: 51413
        unifi-1900: 1900
        unifi-3478: 3478
        unifi-5514: 5514
        unifi-6789: 6789
        unifi-8080: 8080
        unifi-10001: 10001
        whisper-10300: 10300
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: ${TIMEZONE}
      service:
        loadBalancerIP: ${SVC_NGINX_INTERNAL_ADDR}
      publishService:
        enabled: true
      electionID: nginx-internal-controller-leader
      ingressClass: nginx-internal
      ingressClassResource:
        default: true
        name: nginx-internal
        # controllerValue: "k8s.io/ingress-nginx-internal" # Comment this for default ingress
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: 401,403,404,500,501,502,503
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
      #     namespace: networking
      #     namespaceSelector:
      #       any: true
      #   prometheusRule:
      #     enabled: false
      extraArgs:
        default-ssl-certificate: "networking/${SECRET_DOMAIN//./-}-tls"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - ingress-nginx
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - controller
              topologyKey: "kubernetes.io/hostname"
      resources:
        requests:
          memory: 250Mi
          cpu: 100m
        limits:
          memory: 1000Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/181192/custom-error-pages
        tag: 1.2.1
      extraEnvs:
        - name: ERROR_FILES_PATH
          value: ./themes/ghost
