---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m0s
  values:
    tcp:
      "6789": "infrastructure/unifi:mobile-test"
      "8080": "infrastructure/unifi:device-comms"
      "32400": "media/plex:32400"
    udp:
      "3478": "infrastructure/unifi:stun"
      "5514": "infrastructure/unifi:syslog"
      "10001": "infrastructure/unifi:ap-discovery"
      "32410": "media/plex:32410"
      "32412": "media/plex:32412"
      "32413": "media/plex:32413"
      "32414": "media/plex:32414"
