---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  chart:
    spec:
      chart: descheduler
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 5m0s
  values:
    kind: Deployment
    deschedulerPolicy:
      strategies:
        LowNodeUtilization:
          enabled: false
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingNodeTaints:
          enabled: true
