---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: transmission
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    env:
      TZ: "Europe/Rome"
      TRANSMISSION_ALT_SPEED_DOWN: 500
      TRANSMISSION_ALT_SPEED_ENABLED: false
      TRANSMISSION_ALT_SPEED_TIME_BEGIN: 540
      TRANSMISSION_ALT_SPEED_TIME_DAY: 62
      TRANSMISSION_ALT_SPEED_TIME_ENABLED: true
      TRANSMISSION_ALT_SPEED_TIME_END: 1080
      TRANSMISSION_ALT_SPEED_UP: 5
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
      TRANSMISSION_RATIO_LIMIT_ENABLED: true
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_WEB_HOME: "/config/flood-for-transmission/"
    initContainers:
      custom-webui:
        name: custom-webui
        image: curlimages/curl:7.76.1
        command:
          - "/bin/sh"
          - "-c"
          - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 568
          runAsGroup: 568
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 9091
          utptcp:
            enabled: true
            port: 51413
            protocol: TCP
          utpudp:
            enabled: true
            port: 51413
            protocol: UDP
    persistence:
      config:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: longhorn
      downloads:
        enabled: true
        mountPath: /downloads
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/kubernetes/downloads"
            server: "${TRUENAS_ADDR}"
      # watch:
      #   enabled: true
      #   mountPath: /watch
    podSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
