---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  chart:
    spec:
      chart: transmission
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 8.0.1
  interval: 10m0s
  values:
    env:
      TZ: "Europe/Rome"
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
      TRANSMISSION_RPC_PASSWORD: "CHANGEME"
      # TRANSMISSION_WEB_HOME: "/config/flood-for-transmission/"
    initContainers:
      # custom-webui:
      #   name: custom-webui
      #   image: curlimages/curl:7.76.1
      #   command:
      #     - "/bin/sh"
      #     - "-c"
      #     - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
      #   volumeMounts:
      #     - name: config
      #       mountPath: /config
      #   securityContext:
      #     runAsUser: 568
      #     runAsGroup: 568
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 9091
          utptcp:
            enabled: true
            port: 51413
            protocol: TCP
          utpudp:
            enabled: true
            port: 51413
            protocol: UDP
    persistence:
      # config:
      #   enabled: true
      #   type: emptyDir
      # downloads:
      #   enabled: true
      #   mountPath: /downloads
      # watch:
      #   enabled: true
      #   mountPath: /watch
