---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/transmission
              tag: 4.0.4
              pullPolicy: IfNotPresent
            probes:
              liveness:
                spec:
                  timeoutSeconds: 2
              readiness:
                spec:
                  timeoutSeconds: 2
              startup:
                spec:
                  timeoutSeconds: 2
            env:
              TZ: "${TIMEZONE}"
              PUID: 568
              PGID: 1003
              PEERPORT: 51413
            resources:
              requests:
                cpu: 15m
                memory: 50Mi
              limits:
                # cpu: 500m
                memory: 0.5Gi
        strategy: Recreate
    # initContainers:
    #   custom-webui:
    #     name: custom-webui
    #     image: curlimages/curl:8.00.1
    #     command:
    #       - "/bin/sh"
    #       - "-c"
    #       - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
    #     volumeMounts:
    #       - name: config
    #         mountPath: /config
    #     securityContext:
    #       runAsUser: 568
    #       runAsGroup: 568
    service:
      main:
        ports:
          http:
            port: 9091
          utp-tcp:
            enabled: true
            port: 51413
            protocol: TCP
          utp-udp:
            enabled: true
            port: 51413
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "cloud-download"
        hosts:
          - host: &host "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: transmission-tls
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: transmission-config-v1
        globalMounts:
          - path: /config
      downloads:
        enabled: true
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: "/mnt/tank/downloads"
        globalMounts:
          - path: /downloads
      # watch:
      #   globalMounts:
      #     - path: /watch
