---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 10m0s
  values:
    configInline:
      peers:
        - peer-address: "${GATEWAY_ADDR}"
          peer-asn: 64512
          my-asn: 65400
      address-pools:
        - name: bgp
          protocol: bgp
          addresses:
            - "${NETWORK_METALB_CIDR}"
          avoid-buggy-ips: true
