---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-v2
  namespace: infrastructure
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
