---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-v1
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
