---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.1.68
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
      JVM_MAX_HEAP_SIZE: 250M
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "wifi"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: unifi-config-v1
    resources:
      requests:
        cpu: 475m
        memory: 978M
      limits:
        cpu: 796m
        memory: 1243M
