---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/unifi-network-application
              tag: 8.1.113
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              PUID: 1000
              PGID: 1000
              MEM_LIMIT: "250"
            envFrom:
              - secretRef:
                  name: unifi-mongo
            resources:
              requests:
                cpu: 475m
                memory: 978M
              limits:
                cpu: 796m
                memory: 1243M
        strategy: Recreate
    service:
      main:
        controller: main
        ports:
          http:
            port: 8443
            protocol: HTTPS
          guest-http:
            enabled: false
            port: 8880
            protocol: HTTP
          guest-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          device-comms:
            port: 8080
            protocol: TCP
          mobile-test:
            port: 6789
            protocol: TCP
          syslog:
            port: 5514
            protocol: TCP
          stun:
            port: 3478
            protocol: UDP
          l2-discovery:
            port: 1900
            protocol: UDP
          ap-discovery:
            port: 10001
            protocol: UDP
      direct:
        controller: main
        type: LoadBalancer
        loadBalancerIP: ${SVC_UNIFIDIRECT_ADDR}
        ports:
          device-comms:
            enabled: true
            port: 8080
            protocol: TCP
          discovery:
            enabled: true
            port: 1900
            protocol: UDP
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "admin"
          hajimari.io/icon: "wifi"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: unifi-tls
    # portal:
    #   enabled: false
    #   className: "nginx-internal"
    #   annotations:
    #     cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #     hosts:
    #       - host: &host-guest "guest.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               port: guest-https
    #     tls:
    #       - hosts:
    #           - *host-guest
    #         secretName: unifi-guest-tls
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: unifi-config-v2
        globalMounts:
          - path: /config
