---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infrastructure
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: unifi
      version: 4.6.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.5.55
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Rome"
      JVM_INIT_HEAP_SIZE: 100M
      JVM_MAX_HEAP_SIZE: 250M
      LOTSOFDEVICES: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "wifi"
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "unifi.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: infra-unifi-config-v1
    resources:
      requests:
        cpu: 475m
        memory: 978M
      limits:
        cpu: 796m
        memory: 1243M
    mongodb:
      enabled: true
      architecture: standalone
      image:
        # Currently no arm64 image (https://github.com/bitnami/charts/issues/7305)
        repository: mongo
        tag: 5.0.5
      master:
        persistence:
          enabled: true
        existingClaim: infra-unifi-mongodb-v1
