---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/unifi-controller
              tag: 7.5.176
              pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: "${TIMEZONE}"
      PUID: 999
      PGID: 999
      MEM_LIMIT: "250"
    service:
      main:
        ports:
          http:
            port: 8443
            protocol: HTTPS
          guest-http:
            enabled: false
            port: 8880
            protocol: HTTP
          guest-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          device-comms:
            enabled: true
            port: 8080
            protocol: TCP
          mobile-test:
            enabled: true
            port: 6789
            protocol: TCP
          syslog:
            enabled: true
            port: 5514
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      main:
        className: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/group: "admin"
          hajimari.io/icon: "wifi"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: unifi-tls
    # portal:
    #   enabled: false
    #   className: "nginx-internal"
    #   annotations:
    #     cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #     hosts:
    #       - host: &host-guest "guest.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               port: guest-https
    #     tls:
    #       - hosts:
    #           - *host-guest
    #         secretName: unifi-guest-tls
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: unifi-config-v1
        globalMounts:
          - path: /config
    resources:
      requests:
        cpu: 475m
        memory: 978M
      limits:
        cpu: 796m
        memory: 1243M
