---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: lscr.io/linuxserver/unifi-controller
      tag: 7.3.83
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: "${TIMEZONE}"
      PUID: 999
      PGID: 999
      MEM_LIMIT: "250"
    service:
      main:
        ports:
          http:
            port: 8443
            protocol: HTTPS
          guest-http:
            enabled: false
            port: 8880
            protocol: HTTP
          guest-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          device-comms:
            enabled: true
            port: 8080
            protocol: TCP
          mobile-test:
            enabled: true
            port: 6789
            protocol: TCP
          syslog:
            enabled: true
            port: 5514
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-1"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "wifi"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: unifi-config-v1
        mountPath: /config
    resources:
      requests:
        cpu: 475m
        memory: 978M
      limits:
        cpu: 796m
        memory: 1243M
