---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-backups-v1
  namespace: infrastructure
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/tank/kubernetes
    server: ${TRUENAS_ADDR}
  mountOptions:
    - nfsvers=4.2
