---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: postgresql
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    strategy:
      type: Recreate
    architecture: standalone
    clusterDomain: "${SECRET_DOMAIN}"
    global:
      postgresql:
        auth:
          postgresPassword: "${SECRET_POSTGRES_PASSWORD}"
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-primary-v1
      service:
        type: LoadBalancer
        loadBalancerIP: "${SVC_POSTGRESQL_ADDR}"
    diagnosticMode: # All probes will be disabled and the command will be overridden with sleep infinity
      enabled: false
    backup:
      enabled: true
      cronjob:
        schedule: "@daily"
        storage:
          existingClaim: postgresql-backups-v1
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
