---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-16
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: postgresql
      version: 13.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: bitnami/postgresql
      tag: 16.0.0-debian-11-r13
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    architecture: standalone
    clusterDomain: "${SECRET_DOMAIN}"
    global:
      postgresql:
        auth:
          postgresPassword: "${SECRET_POSTGRES_PASSWORD}"
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-primary-v2
      service:
        type: LoadBalancer
    diagnosticMode: # All probes will be disabled and the command will be overridden with sleep infinity
      enabled: false
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
