---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  chart:
    spec:
      chart: reloader
      version: 1.0.74
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  interval: 5m0s
  values:
    nameOverride: reloader
    fullnameOverride: reloader
    podMonitor:
      enabled: true
      namespace: kube-system
