---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      version: v0.0.103
  interval: 5m0s
  values:
    podMonitor:
      enabled: true
      namespace: kube-system
