---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.17.4
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PAPERLESS_OCR_LANGUAGE: ita+eng
      PAPERLESS_REDIS: redis://:${SECRET_REDIS_PASSWORD}@redis-master.infrastructure:6379
      PAPERLESS_TIME_ZONE: "${TIMEZONE}"
      PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
      PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
      PAPERLESS_WORKER_TIMEOUT: 3600 # 1h
    envFrom:
      - secretRef:
          name: paperless-db
    controller:
      annotations:
        secret.reloader.stakater.com/reload: paperless-db
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "leaf"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: paperless-tls
    persistence:
      # -- Configure persistence for data.
      data:
        enabled: true
        mountPath: /usr/src/paperless/data
        type: pvc
        existingClaim: paperless-data-v1
      # -- Configure persistence for media.
      media:
        enabled: true
        mountPath: /usr/src/paperless/media
        type: pvc
        existingClaim: paperless-media-v1
      # -- Configure volume to monitor for new documents.
      consume:
        enabled: true
        mountPath: /usr/src/paperless/consume
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        subPath: Paperless/consume
      # -- Configure export volume.
      export:
        enabled: true
        mountPath: /usr/src/paperless/export
        type: nfs
        server: "${TRUENAS_ADDR}"
        path: /mnt/tank/media
        subPath: Paperless/export
    resources:
      requests:
        memory: 0.5Gi
        cpu: 100m
      limits:
        memory: 2Gi
    probes:
      liveness:
        spec:
          timeoutSeconds: 3
      readiness:
        spec:
          timeoutSeconds: 3
    sidecars:
      gotenberg:
        image: gotenberg/gotenberg:7.9.1
        ports:
          - containerPort: 3000
        command:
          - "gotenberg"
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/.*"
      tika:
        image: ghcr.io/paperless-ngx/tika:2.9.0-minimal
        ports:
          - containerPort: 9998
