---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kured
      version: 5.4.5
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: ghcr.io/kubereboot/kured
    configuration:
      timeZone: "${TIMEZONE}"
      startTime: "10pm"
      endTime: "2am"
      notifyUrl: "${SECRET_KURED_WEBHOOK}"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    metrics:
      create: false # disable until prometheus works
