---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  interval: 5m0s
  values:
    configuration:
      timeZone: "Europe/Rome"
      startTime: "10pm"
      endTime: "2am"
      notifyUrl: "${SECRET_KURED_WEBHOOK}"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    nodeSelector:
      # Currently no arm64 image (https://github.com/weaveworks/kured/issues/23)
      kubernetes.io/arch: amd64
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    metrics:
      create: true
