---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: piper
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: rhasspy/wyoming-piper
              tag: latest
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
            args:
              - --voice
              - it-riccardo_fasol-x-low
        strategy: Recreate
    service:
      main:
        ports:
          http:
            enabled: false
          tcp:
            port: 10200
            protocol: TCP
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /data
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
