---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: paperless
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  install:
    createNamespace: true
  values:
    image:
      repository: jonaswinkler/paperless-ng
      tag: 1.5.0
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
      PAPERLESS_REDIS: redis://paperless-redis-master:6379
      PAPERLESS_OCR_LANGUAGE: ita+eng
      PAPERLESS_TIME_ZONE: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "leaf"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      # -- Configure persistence for data.
      data:
        enabled: true
        type: pvc
        existingClaim: paperless-data-v1
      # -- Configure persistence for media.
      media:
        enabled: true
        type: pvc
        existingClaim: paperless-media-v1
      # -- Configure volume to monitor for new documents.
      consume:
        enabled: true
        type: pvc
        existingClaim: paperless-consume-v1
      # -- Configure export volume.
      export:
        enabled: true
        type: pvc
        existingClaim: paperless-export-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    probes:
      liveness:
        spec:
          timeoutSeconds: 3
      readiness:
        spec:
          timeoutSeconds: 3
    redis:
      enabled: true
      architecture: standalone
      image:
        # Currently no arm64 image (https://github.com/bitnami/bitnami-docker-redis/issues/192)
        repository: redis
        tag: 7.0.3
      master:
        persistence:
          enabled: false
