---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: home-cloud
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: paperless
      version: 8.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: jonaswinkler/paperless-ng
      tag: 1.5.0
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Rome
      PAPERLESS_REDIS: redis://paperless-redis-master:6379
      PAPERLESS_OCR_LANGUAGE: ita+eng
      PAPERLESS_TIME_ZONE: "Europe/Rome"
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "leaf"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - "paperless.${SECRET_DOMAIN}"
    persistence:
      # -- Configure persistence for data.
      data:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: longhorn
      # -- Configure persistence for media.
      media:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 250Mi
        storageClass: longhorn
      # -- Configure volume to monitor for new documents.
      consume:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 50Mi
        storageClass: longhorn
      # -- Configure export volume.
      export:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 50Mi
        storageClass: longhorn
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    redis:
      enabled: true
      architecture: standalone
