---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db-operator
  namespace: db-operator
spec:
  chart:
    spec:
      chart: db-operator
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: kloeckneri
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/kloeckner-i/db-operator
      tag: 1.10.0
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
