apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
data:
    api-token: ENC[AES256_GCM,data:v8ZMjPBub0EmMpHgNYjerwR41BPj9Vtc1K/CjWMtaGW9U0jbZrYrr2I3zU4S0kLpKGlk5vh0qJMP8p5i,iv:hUv371CAx+CZREqpz5W4oYT45quHezACMa2uNKWtHaw=,tag:9X4dA7cmlfUMzE9EdUaJMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL1RqRk5vb2VLNFpYR090
            MitMT2s4c214Qkp2V1drNmdCdnlqOENyaDFBCmM5RXBzOVl2KzF2eklVNEg0Vjhu
            Qm9QSjVmc3l6MFZwVW1xZWdSQ2ZVZ1EKLS0tIFJ3KzNHR0kvZllVNE55REc0ZjQ3
            Z1ExT0o1WTRWbEFKUVBsZytIYmptTncKtGaEZkhuua6S8jOy1XU6QwsTUQ9CpsXq
            MXJWGKx5E2hB6ZncHtD9q++2IllbpitKzLB49r6cHU/Zk3tjnWH5jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T22:21:42Z"
    mac: ENC[AES256_GCM,data:CMjyE6Ucdw+crwkfc+HMT6pfBDlZssCyir4XndJfT3iIKGpaOyMDPbmhdc/9bcDnFIf3IC4o0jC/OapM8vQbVfA30fcNDBgqpUtXrRR3Sf5F4NOygHFwz+cAW+EdteAZ5z8qL/NvGrlSwuRoPEESoZd4dYxvKyU8mVu5hhzBeYU=,iv:i8g2QyN8uI6eSIwFSh3O/34KbxUMozhNlE6LhyVvj+k=,tag:aiAfuW3nOE/29QT4SbR5qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
