---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.11.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 10m0s
  values:
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
