---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-v1
  namespace: media
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
