---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readarr-downloads
  namespace: media
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: readarr-downloads
  storageClassName: smb
