---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  chart:
    spec:
      chart: readarr
      version: 6.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.1.1352
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "bookshelf"
        hosts:
          - host: &host "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: readarr-config-v1
      books:
        enabled: true
        mountPath: /books
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media/Books"
            server: "${TRUENAS_ADDR}"
      downloads:
        enabled: true
        mountPath: /downloads
        type: pvc
        existingClaim: downloads
        subPath: complete/books
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 1003
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 15m
        memory: 0.5G
      limits:
        # cpu: 500m
        memory: 1G
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
