---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: readarr
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.1149
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Rome
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "bookshelf"
        hosts:
          - host: "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "readarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 0.5Gi
        storageClass: longhorn
      books:
        enabled: true
        mountPath: /books
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/user/media/Books"
            server: "${UNRAID_ADDR}"
      downloads:
        enabled: true
        mountPath: /downloads
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/kubernetes/downloads/complete/books"
            server: "${TRUENAS_ADDR}"
    podSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
