---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: readarr
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.1189
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Rome
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
          hajimari.io/icon: "bookshelf"
        hosts:
          - host: "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "readarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        retain: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 0.5Gi
        storageClass: longhorn
      books:
        enabled: true
        mountPath: /books
        type: custom
        volumeSpec:
          nfs:
            path: "/mnt/tank/media/Books"
            server: "${TRUENAS_ADDR}"
      downloads:
        enabled: true
        mountPath: /downloads
        type: pvc
        existingClaim: downloads
        subPath: complete/books
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 1003
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 15m
        memory: 324M
      limits:
        # cpu: 500m
        memory: 747M
    probes:
      liveness:
        spec:
          timeoutSeconds: 2
      readiness:
        spec:
          timeoutSeconds: 2
      startup:
        spec:
          timeoutSeconds: 2
