---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: kube-system
spec:
  chart:
    spec:
      chart: harbor
      version: 19.9.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    strategy:
      type: Recreate
    clusterDomain: "${SECRET_DOMAIN}"


    auth:
      rootUser: root
      rootPassword: "${SECRET_MONGODB_PASSWORD}"
    persistence:
      enabled: true
      existingClaim: mongodb-primary-v1
    service:
      type: LoadBalancer
      loadBalancerIP: "${SVC_MONGODB_ADDR}"
    diagnosticMode: # All probes will be disabled and the command will be overridden with sleep infinity
      enabled: false
    metrics:
      enabled: false
