---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
    - "${NETWORK_METALB_ADDRS}"
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-bgp
  namespace: metallb-system
spec:
  addresses:
    - "${NETWORK_METALB_ADDRS_BGP}"
