---
name: Schedule - Renovate Annotations Update

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  renovate-annotations-update:
    name: Renovate Annotations Update
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: "./cluster"
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-annotations
          delete-branch: true
          title: "chore(ci): update renovate annotations"
          signoff: true
          committer: "GiorgioAresu <GiorgioAresu@users.noreply.github.com>"
          author: "GiorgioAresu <giorgioaresu@users.noreply.github.com>"
          assignees: "GiorgioAresu"
          commit-message: "chore(ci): update renovate annotations"
          body: |
            Update Helm Releases in order for Renovate to pick up new versions of Helm charts
          labels: component/ci
